### ISSUE TITLE
Bump bpaf to fix the broken completions

### ISSUE THREAD

**Issue by dgudim** [VorpalBlade/chezmoi_modify_manager#50]
In some cases completions broke for me (albeit, when i was misusing them, but still a bug). Turns out it's a bpaf bug. 

Original issue: https://github.com/akinomyoga/ble.sh/issues/368

It was already reported to bpaf, we just need to wait

**Comment by VorpalBlade** [comment]
Is it [this](https://github.com/pacak/bpaf/issues/303) bpaf issue that I reported or yet another one? If so, could you link it here so I can keep track of it.

**Comment by VorpalBlade** [comment]
Hm, seems to be a different one: https://github.com/pacak/bpaf/pull/311

I don't use bash so I wouldn't have noticed it. It would be great to have tests of the completion that bpaf outputs somehow, but it seems quite complicated. Especially since executing the binary from tests tend to break when cross compiling.

**Comment by pacak** [comment]
0.9.6 is out

**Comment by VorpalBlade** [comment]
This will be included 2.2.0 that is being built as of writing this.

Note that the actual completions themself are still broken pending @pacak fixes https://github.com/pacak/bpaf/issues/303 (no pressure). But at least it should just do nothing instead of error out.

Though I haven't tried this with bash, as I'm not set up to test that. I would like to add auto tests for the completion at a future point, probably once the above mentioned issue is solved (would be kind of pointless while it is still broken).
