### ISSUE TITLE
Add native (M1) macos binary to release

### ISSUE THREAD

**Issue by glensc** [VorpalBlade/chezmoi_modify_manager#69]
## Is your feature request related to a problem? Please describe.

The latest release contains only x86_64 version for macos:
- https://github.com/VorpalBlade/chezmoi_modify_manager/releases/tag/v3.0.0

## Describe the solution you'd like

build aarch64 version for m1

## Describe alternatives you've considered

Surely can run x86_64 using Rosetta 2, but would prefer native binaries

## Additional context

I came here from chezmoi addons page, found no brew install
- https://www.chezmoi.io/links/related-software/#githubcomvorpalbladechezmoi_modify_manager

**Comment by VorpalBlade** [comment]
I don't have a Mac myself, so I can't build that. Unfortunately GitHub CI only offers (free) x86-64 Mac builds, and I was not able to get cross compiling in CI working for ARM based Mac.

Nor would I have the ability to run tests in CI on it (since I believe Rosetta only allows running x86-64 programs on ARM, not the reverse.

However, contributions are welcome. Some minimum requirements though:

* It has to build in free GitHub CI. I'm not paying for my hobby project.
* It has to not just cross compile but also be able to run tests, in a VM is acceptable (that is how it works for Linux ARM etc, it uses qemu to run the tests).

As for brew, I have no clue how that works, not having a Mac. Is it like package management on Linux, where the maintainer could be separate from the upstream? If so, I don't see any reason why someone else who wants this could make a package for it (hint hint).

**Comment by VorpalBlade** [comment]
Closing this, as there doesn't seem to be any interest from the reporter in making this work. Feel free to get back with a PR though that implements any parts of this (either CI builds with testing as well as releases, or packages for things like brew/macports/whatever else there is).

**Comment by glensc** [comment]
1. brew is available on linux too: https://brew.sh/
2. you can host your own repo for brew recipes: https://github.com/Homebrew/brew/blob/bc056d2aa6ae689a8e0d7e484ddc2f424f3c6d35/docs/Taps.md

few tap examples:
- https://github.com/glensc/homebrew-tap (mine)
- https://github.com/minio/homebrew-stable

minio tap shows examples how to do cross platform values.

what could be done here is to add recipe that does source build. uploading binary builds, as noted requires resources that are not available in free tier.

I understand you have zero interest in this. just sharing some information.

**Comment by VorpalBlade** [comment]
@glensc I don't use brew myself (and have no plans to do so either, since we have native package managers that work well already), but contributions are welcome.

**Comment by VorpalBlade** [comment]
I recently added a file with some useful tips if you want to package chezmoi_modify_manager: https://github.com/VorpalBlade/chezmoi_modify_manager/blob/main/doc/for-packagers.md

With regards to a hosted brew repository that sounds interesting since a CI job could be added to update that automatically whenever I made a release (that is how the AUR package gets updated, I automate everything for releases, all I have to do is tag a release and sit back and wait).

In that scenario I envision this is how it would work out:

* I get help by someone interested in this in setting up the brew repository and the required CI hooks for the release job. Or they could go do this completely on their own (rather than under my github account), but then having it auto-update on release would probably be difficult.
* The brew repository itself contains a CI hook that verifies that the brew package works (somehow, maybe it tries installing it on a MacOS runner and running the binary to check that the basics work?)

I also see that brew seems to use Ruby. I don't know any ruby at all, so that would be another barrier to me trying to do this on my own (it became even less likely in other words).

**Comment by VorpalBlade** [comment]
Apparently Cirrus CI has support for M1 and is available for free for open source.

This could be one option for anyone who wants to implement support for pre-built M1 binaries:

* https://cirrus-ci.org/guide/macOS/
* https://cirrus-ci.org/faq/#are-there-any-limits

They also supports FreeBSD apparently, that would be great to have too.

Downside is of course that there is more complexity to use two different CI systems at the same time (and I don't see myself migrating everything else from Github Actions as things currently are).

**Comment by VorpalBlade** [comment]
There seem to be native ARM64 runners in the general Github MacOS runner pool now. It is worth looking into if this is guaranteed or how it works. It opens the possibility of adding a native ARM64 build
